"""拼音题库 — 汉字 + 拼音对照"""

PINYIN_TEXTS = [
    {"chinese": "我是一名学生", "pinyin": "wo shi yi ming xue sheng"},
    {"chinese": "今天天气真好", "pinyin": "jin tian tian qi zhen hao"},
    {"chinese": "我喜欢学习拼音", "pinyin": "wo xi huan xue xi pin yin"},
    {"chinese": "中国是一个伟大的国家", "pinyin": "zhong guo shi yi ge wei da de guo jia"},
    {"chinese": "学习语言需要坚持不懈", "pinyin": "xue xi yu yan xu yao jian chi bu xie"},
    {"chinese": "春天来了花儿开了", "pinyin": "chun tian lai le hua er kai le"},
    {"chinese": "请你帮我一个忙好吗", "pinyin": "qing ni bang wo yi ge mang hao ma"},
    {"chinese": "我们都是好朋友", "pinyin": "wo men dou shi hao peng you"},
    {"chinese": "明天我们去公园玩", "pinyin": "ming tian wo men qu gong yuan wan"},
    {"chinese": "老师说要好好学习天天向上", "pinyin": "lao shi shuo hao hao xue xi tian tian xiang shang"},
    {"chinese": "电脑是现代化的工具", "pinyin": "dian nao shi xian dai hua de gong ju"},
    {"chinese": "朋友是生命中最美好的礼物", "pinyin": "peng you shi sheng ming zhong zui hao de li wu"},
    {"chinese": "健康的身体非常重要", "pinyin": "jian kang de shen ti fei chang zhong yao"},
    {"chinese": "书是我们进步的阶梯", "pinyin": "shu shi wo men jin bu de jie ti"},
    {"chinese": "计算机科学发展很快", "pinyin": "ji suan ji ke xue fa zhan hen kuai"},
    {"chinese": "科学技术改变了世界", "pinyin": "ke xue ji shu gai bian le shi jie"},
    {"chinese": "历史是一面镜子", "pinyin": "li shi shi yi mian jing zi"},
    {"chinese": "地理能帮助了解世界", "pinyin": "di li neng bang zhu liao jie shi jie"},
    {"chinese": "语言是交流的工具", "pinyin": "yu yan shi jiao liu de gong ju"},
    {"chinese": "创新是进步的灵魂", "pinyin": "chuang xin shi jin bu de ling hun"},
    {"chinese": "努力学习把握未来", "pinyin": "nu li xue xi ba wo wei lai"},
    {"chinese": "家庭是最温暖的港湾", "pinyin": "jia ting shi zui wen nuan de gang wan"},
    {"chinese": "爱护环境人人有责", "pinyin": "ai hu huan jing ren ren you ze"},
    {"chinese": "文化多样性是世界的色彩", "pinyin": "wen hua duo yang xing shi shi jie de se cai"},
    {"chinese": "科学技术让生活更美好", "pinyin": "ke xue ji shu rang sheng huo geng mei hao"},
    {"chinese": "运动能使人保持活力", "pinyin": "yun dong neng shi ren bao chi huo li"},
    {"chinese": "音乐可以慰藉感情", "pinyin": "yin yue ke yi wei jie gan qing"},
    {"chinese": "美术提高人的审美能力", "pinyin": "mei shu ti gao ren de shen mei neng li"},
    {"chinese": "动物是人类的朋友", "pinyin": "dong wu shi ren lei de peng you"},
    {"chinese": "植物为地球带来生机", "pinyin": "zhi wu wei di qiu dai lai sheng ji"},
    {"chinese": "太阳每天从东方升起", "pinyin": "tai yang mei tian cong dong fang sheng qi"},
    {"chinese": "星星在夜晚闪烁", "pinyin": "xing xing zai ye wan shan shuo"},
    {"chinese": "月亮带给我们梦想", "pinyin": "yue liang dai gei wo men meng xiang"},
    {"chinese": "海洋包含着无穷的奥秘", "pinyin": "hai yang bao han zhe wu qiong de ao mi"},
    {"chinese": "森林是地球的肺部", "pinyin": "sen lin shi di qiu de fei bu"},
    {"chinese": "空气清新对健康有益", "pinyin": "kong qi qing xin dui jian kang you yi"},
    {"chinese": "水是生命的源泉", "pinyin": "shui shi sheng ming de yuan quan"},
    {"chinese": "蔬菜水果营养丰富", "pinyin": "shu cai shui guo ying yang feng fu"},
    {"chinese": "早睡早起身体好", "pinyin": "zao shui zao qi shen ti hao"},
    {"chinese": "微笑能够拉近距离", "pinyin": "wei xiao neng gou la jin ju li"},
    {"chinese": "谢谢你的帮助", "pinyin": "xie xie ni de bang zhu"},
    {"chinese": "祝你身体健康", "pinyin": "zhu ni shen ti jian kang"},
    {"chinese": "学习需要耐心和恒心", "pinyin": "xue xi xu yao nai xin he heng xin"},
    {"chinese": "每个人都有自己的梦想", "pinyin": "mei ge ren dou you zi ji de meng xiang"},
    {"chinese": "知识就是力量", "pinyin": "zhi shi jiu shi li liang"},
    {"chinese": "团结就是力量", "pinyin": "tuan jie jiu shi li liang"},
    {"chinese": "故事能给我们启发", "pinyin": "gu shi neng gei wo men qi fa"},
    {"chinese": "天空中飘着白云", "pinyin": "tian kong zhong piao zhe bai yun"},
    {"chinese": "小河流水清又清", "pinyin": "xiao he liu shui qing you qing"},
    {"chinese": "一年之计在于春", "pinyin": "yi nian zhi ji zai yu chun"},
    {"chinese": "勤能补拙是良训", "pinyin": "qin neng bu zhuo shi liang xun"},
    {"chinese": "天才在于积累", "pinyin": "tian cai zai yu ji lei"},
    {"chinese": "聪明在于勤奋", "pinyin": "cong ming zai yu qin fen"},
    {"chinese": "书山有路勤为径", "pinyin": "shu shan you lu qin wei jing"},
    {"chinese": "学海无涯苦作舟", "pinyin": "xue hai wu ya ku zuo zhou"},
    {"chinese": "温故而知新", "pinyin": "wen gu er zhi xin"},
    {"chinese": "三人行必有我师", "pinyin": "san ren xing bi you wo shi"},
    {"chinese": "坚持锻炼身体好", "pinyin": "jian chi duan lian shen ti hao"},
    {"chinese": "多喝温开水有益健康", "pinyin": "duo he wen kai shui you yi jian kang"},
    {"chinese": "兴趣是最好的老师", "pinyin": "xing qu shi zui hao de lao shi"},
    {"chinese": "勇气面对困难", "pinyin": "yong qi mian dui kun nan"},
    {"chinese": "智慧在于积累", "pinyin": "zhi hui zai yu ji lei"},
    {"chinese": "好好学习天天向上", "pinyin": "hao hao xue xi tian tian xiang shang"},
    {"chinese": "为了梦想而奋斗", "pinyin": "wei le meng xiang er fen dou"},
    {"chinese": "把握每一天的时间", "pinyin": "ba wo mei yi tian de shi jian"},
    {"chinese": "做事要一心一意", "pinyin": "zuo shi yao yi xin yi yi"},
    {"chinese": "不怕困难勇往直前", "pinyin": "bu pa kun nan yong wang zhi qian"},
    {"chinese": "爱国是一种伟大的情感", "pinyin": "ai guo shi yi zhong wei da de qing gan"},
    {"chinese": "学习语言要多听多说", "pinyin": "xue xi yu yan yao duo ting duo shuo"},
    {"chinese": "多读书读好书", "pinyin": "duo du shu du hao shu"},
    {"chinese": "千万别放弃", "pinyin": "qian wan bie fang qi"},
    {"chinese": "条条大路通罗马", "pinyin": "tiao tiao da lu tong luo ma"},
    {"chinese": "只要努力就会进步", "pinyin": "zhi yao nu li jiu hui jin bu"},
    {"chinese": "自信是成功的第一步", "pinyin": "zi xin shi cheng gong de di yi bu"},
    {"chinese": "关键是要行动起来", "pinyin": "guan jian shi yao xing dong qi lai"},
    {"chinese": "理想指引前进方向", "pinyin": "li xiang zhi yin qian jin fang xiang"},
    {"chinese": "热情让生活更精彩", "pinyin": "re qing rang sheng huo geng jing cai"},
    {"chinese": "珍惜身边的每一刻", "pinyin": "zhen xi shen bian de mei yi ke"},
    {"chinese": "感恩让生活更美好", "pinyin": "gan en rang sheng huo geng mei hao"},
    {"chinese": "分享是一种快乐", "pinyin": "fen xiang shi yi zhong kuai le"},
    {"chinese": "合作能产生力量", "pinyin": "he zuo neng chan sheng li liang"},
    {"chinese": "尊重他人是基本的礼貌", "pinyin": "zun zhong ta ren shi ji ben de li mao"},
]

PINYIN_LONG_TEXTS = [
    {"chinese": "我们生活在一个美丽的世界里，这里有蓝天白云，有绿树红花，还有可爱的小动物。我们应该爱护环境，保护我们的地球。",
     "pinyin": "wo men sheng huo zai yi ge mei li de shi jie li, zhe li you lan tian bai yun, you lv shu hong hua, hai you ke ai de xiao dong wu. wo men ying gai ai hu huan jing, bao hu wo men de di qiu."},
    {"chinese": "学习是一件非常有趣的事情。每天我们都能学到新的知识，认识新的事物。只要我们用心去学，就一定能够进步。",
     "pinyin": "xue xi shi yi jian fei chang you qu de shi qing. mei tian wo men dou neng xue dao xin de zhi shi, ren shi xin de shi wu. zhi yao wo men yong xin qu xue, jiu yi ding neng gou jin bu."},
    {"chinese": "朋友是我们生命中非常重要的人。他们在我们开心时与我们分享欢乐，在我们难过时给我们安慰。珍惜身边的每一位朋友吧。",
     "pinyin": "peng you shi wo men sheng ming zhong fei chang zhong yao de ren. ta men zai wo men kai xin shi yu wo men fen xiang huan le, zai wo men nan guo shi gei wo men an wei. zhen xi shen bian de mei yi wei peng you ba."},
    {"chinese": "科学技术让我们的生活变得更加方便。电脑和手机帮助我们联系世界，互联网让我们获取大量信息。但我们也要注意合理使用。",
     "pinyin": "ke xue ji shu rang wo men de sheng huo bian de geng jia fang bian. dian nao he shou ji bang zhu wo men lian xi shi jie, hu lian wang rang wo men huo qu da liang xin xi. dan wo men ye yao zhu yi he li shi yong."},
]


def get_pinyin_text(difficulty="short"):
    import random
    pool = PINYIN_LONG_TEXTS if difficulty == "long" else PINYIN_TEXTS
    return random.choice(pool)
